---
# - hosts: all

# pre_tasks:

# - name: Setting mac address facts
#   when:
#   ansible.builtin.set_fact:
#     one_fact: something
#     other_fact: "{{ local_var * 2 }}"
#     another_fact: "{{ some_registered_var.results | map(attribute='ansible_facts.some_fact') | list }}"

- hosts: h-gateway-instance
  tasks:
    - name: Use gateway
      include_role:
        name: gateway

- hosts: h-dhcp-instance
  tasks:
    - name: Use dhcp
      include_role:
        name: dhcp


# - hosts: h-dns-instance
#   tasks:
#     - name: Use dns
#       include_role:
#         name: dns