- hosts: h-gateway-instance
  tasks:
    - name: Use gateway
      include_role:
        name: gateway

- hosts: h-dhcp-instance
  tasks:
    - name: Use dhcp
      include_role:
        name: dhcp

# - hosts: h-dns-instance
#   tasks:
#     - name: Use dns
#       include_role:
#         name: dns