---
- name: Update subscription manager
  command: subscription-manager refresh

- name: Install dhcp-server
  become_user: root
  yum:
    name: dhcp

- name: /etc/sysconfig/network-scripts/ifcfg-ens224
  blockinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-ens224
    block: |
      DNS1={{ dns_ip }} ;
      DEFROUTE=yes
      DOMAIN={{ domain_name }}
      GATEWAY={{ gateway_ip }} ;


- name: /etc/dhcp/dhcpd.conf config
  become_user: root
  blockinfile:
    dest: /etc/dhcp/dhcpd.conf
    block: |
      option domain-name "{{ domain_name }}" ;
      default-lease-time 86400 ;
      max-lease-time 172800 ;
      ddns-update-style none ;
      authoritative ;
      subnet {{ subnet }} netmask {{ subnet_mask }} {
              range 10.0.0.10 10.0.0.24 ;
              option subnet-mask {{ subnet_mask }} ;
              option routers {{ gateway_ip }} ; 
              option domain-name-servers {{ dns_ip }} ;  
              option domain-search "{{ domain_name }}" ;
      }
      host gateway-node {
        hardware ethernet {{ gateway_macaddress }} ; 
        fixed-address {{ gateway_ip }};
      }
      host DNS-node {
        hardware ethernet {{ dns_macaddress }} ; 
        fixed-address {{ dns_ip }};
      }


- name: Start DHCP
  service:
    name: dhcpd
    state: started

- name: Add dhcpd service
  ansible.posix.firewalld:
    service: dhcp
    permanent: yes
    state: enabled

- name: Restart firewall
  systemd:
    name: firewalld
    state: restarted


