---
- name: Update subscription manager
  command: subscription-manager refresh

- name: Install dhcp-server
  become_user: root
  yum:
    name: dhcp

- name: /etc/sysconfig/network-scripts/ifcfg-ens224
  blockinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-ens224
    block: |
      DNS1={{ dns_ip | default('default_value') }} ;
      DEFROUTE=yes
      DOMAIN="{{ domain_name | default('default_value') }}"
      GATEWAY={{ gateway | default('default_value') }} ;


- name: /etc/dhcp/dhcpd.conf config
  become_user: root
  blockinfile:
    dest: /etc/dhcp/dhcpd.conf
    block: |
      option domain-name "{{ domain_name | default('default_value') }}";
      default-lease-time 86400 ;
      max-lease-time 172800 ;
      ddns-update-style none ;
      authoritative ;
      subnet {{ subnet| default('default_value') }} netmask {{ subnet-mask | default('default_value') }} {
              range 10.0.0.10 10.0.0.100 ;
              option subnet-mask {{ subnet-mask | default('default_value') }} ;
              option routers {{ gateway | default('default_value') }} ; 
              option domain-name-servers {{ dns_ip | default('default_value') }} ;  
              option domain-search "{{ domain_name | default('default_value') }}";
      }

- name: Start DHCP
  service:
    name: dhcpd
    state: started

- name: Add dhcpd service
  ansible.posix.firewalld:
    service: dhcp
    permanent: yes
    state: enabled

- name: Restart firewall
  systemd:
    name: firewalld
    state: restarted


