---
- name: Update subscription manager
  command: subscription-manager refresh

- name: Install dhcp-server
  become_user: root
  yum:
    name: dhcp

- name: /etc/dhcp/dhcpd.conf config
  become_user: root
  blockinfile:
    dest: /etc/dhcp/dhcpd.conf
    block: |
      option domain-name "harrison";
      default-lease-time 86400 ;
      max-lease-time 172800 ;
      ddns-update-style none ;
      authoritative ;
      subnet 10.0.0.0 netmask 255.255.255.0 {
              range 10.0.0.10 10.0.0.50 ;
              option subnet-mask 255.255.255.0 ;
              option routers 10.0.0.1 ; 
              option domain-name-servers 10.0.0.3 , 8.8.8.8 , 8.8.4.4 ;  
              option domain-search "harrison";
      }

- name: Start DHCP
  service:
    name: dhcpd
    state: started

- name: Add dhcpd service
  ansible.posix.firewalld:
    service: dhcp
    permanent: yes
    state: enabled

- name: Restart firewall
  systemd:
    name: firewalld
    state: restarted


